language: node_js
node_js:
- '0.12'
script:
- bash ./scripts/deploy-to-gh-pages.sh
branches:
only:
- develop
env:
  global:
  - GH_REF: github.com/FrontInJF/frontinjf.github.io.git
  - secure: YWwcVt0O8+4TlU7Vu/4UzGW5VxFYBWjkQvyArqj0CcPrDnxJpWYhQuQlK9PCVFM9Mx+tOlGusc/OP4SudaqcpmSPaRuhULvJ5i6+iLz8aIuP+RDlADQJ+zPFbowsZpKJJlcbBq7Qy/2xx//Hce8USxUvpA25953H2yS/QbQrEXHeVNgtzVcVTlWRb1O3ergWUCZKvnJeXni9vWueB7+vQPfNGUByEx4Fi6xiXjlyVbDmUfo0XV8hwq8WEAyh/3+kZyVd8O1DhOFPvsO3rdZasvSkcCFhkK+t2AD+qtlIGHnxzT3vkXpRldCC8mA52YXccKm5/9qHeLp5pbDFPYQd/O3jkSR3P59jKIjQP3gFODZz1nSkKw+1w6I3Iz0wX8dRDZzHXgc6z2gzaovzxDXrGc3AiiDY64IfibcLqMOygnlGNZbuDdpvi28om6e+W9KkS6u7QPFj0K/2r0qWyBO3apXOihXFlF1UtJOTTfQjfB8agLXYS/bO8MtpKjB76SfvRtPG3A4cf1NaP76firuBvhu2arCZ2SxEzQzTLUIUrBMvtuK89xGvvGb1aLyUlcwcdo+wDyDK4OL1fLKa4VC0RUQKynWPgmFqiNq/IblgmLRZ4P+0lcbYYuWyCebKerlhNhdADXRM1iVONGkHp/t3Y17fwwUeiI8gKNpnFkSaXuk=
